#!/usr/bin/env bash
#check if nginx is running
sudo systemctl status nginx
#if it's not runnong 
sudo systemctl start nginx
#verify firewall settings 
sudo ufw status
#allowing incoming traffic
sudo ufw allow 80
