#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash
# Not allowed to use ps


pids=$(pgrep bash)
for pid in $pids; do
    name=$(cat /proc/$pid/cmdline | tr '\0' ' ')
    echo "PID: $pid, Name: $name"
done
